displayName=Giants' Foundry Gear Values
author=Speshkitty
support=https://github.com/Speshkitty/GiantFoundryItemValues
description=Adds bar values to gear usable in Giants' Foundry
tags=giants foundry, gear
plugins=com.speshkitty.giantsfoundryitemvalues.ItemBarValuesPlugin